controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_users:
    path: '/user/'
    controller: 'App\Controller\UserController::searchUsers'
    methods: ['GET', 'POST']