controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
app_ajouter_panier:
    path: '/ajouter-au-panier/{produit_id}'
    controller: 'App\Controller\PanierController::ajouterPanier'
